### PR TITLE
upgraded quartz version and added delayed start time

### PR DESCRIPTION
**Pull request by erikwj**
This is my first OS contribution, please let me know if I did something wrong.

### CODE REVIEW

**Comment by enragedginger** [comment]
Thank you! I'll look into merging this in.

**Comment by enragedginger** [comment]
After reviewing this a bit, I have a couple of comments:
1. Can you merge master back into your branch? There's a merge conflict resulting from pull request #27.
2. Can you change the startDate parameter to be of type Option[Date] instead of Date and default to None? In the case where it is None, we'll call startNow, and in the other case, we'll call startAt.

Let me know if you have any questions.

**Comment by erikwj** [comment]
Will do

**Comment by erikwj** [comment]
Because the methond `schedul` is overloaded it's not possible to use default parameters. Need some time to figure out how to do this in a neat way.

**Comment by enragedginger** [comment]
I'm not sure that I follow. What's stopping this:
```
def schedule(name: String, receiver: ActorRef, msg: AnyRef, startDate: Option[Date]): Date
```

from being this?:

```
def schedule(name: String, receiver: ActorRef, msg: AnyRef, startDate: Option[Date] = None): Date
```

**Comment by erikwj** [comment]
Because the schedule method is overloaded, it can't have a default parameter according to scalac

**Comment by enragedginger** [comment]
I see what you were referring to about the issues with default parameters and method overloading. I've merged in your changes in #31 along with some other changes. Most notably:

- I updated the version number to 1.5.0. We added the startDate functionality as well as support for actor selection, so I figured that was worthy of a new version number.
- I updated one of the tests to compare seconds as floats instead of longs to avoid issues where the test would fail for poor reasons.
- I updated the README to reflect some of these changes and also fixed some spelling / grammar errors.

**Pull request merged**
