### PR TITLE
Added rescheduleJob method to alllow for rescheduling

### PR DESCRIPTION
**Pull request by ralph-m**
New method encapsulates removing of already existent schedules to allow for rescheduling

### CODE REVIEW

**Comment by enragedginger** [comment]
@ralph-m Can you explain the rationale for this? I'm not quite sure exactly what problem you're trying to solve with this.

**Comment by ralph-m** [comment]
Hi @enragedginger, sure. In order to reschedule an already existent task at runtime one has to delete it from `var schedules` (and invoke `cancelJob()` as well). I thought integrating a method to encapsulate at least the manipulation of `schedules` is a good idea as it is not obvious to the user how to remove an existent schedule in the first place. 

A further thought was having a method similar to the following one in order to provide a proper method for rescheduling a task at runtime.
```
def rescheduleJob(jobSchedule: JobSchedule, actorRef: ActorRef, event: AnyRef): Date = {
  val jobName = jobSchedule.jobName
  cancelJob(jobName)
  schedules = schedules - jobName.toUpperCase
  createSchedule(name = jobName, cronExpression = jobSchedule.cronExpression)
  schedule(jobName, actorRef, event)
}
````

**Comment by enragedginger** [comment]
@ralph-m I think the second approach you mentioned involving a fully functioning rescheduleJob method is the preferable to simply removing the schedule from the map. When you remove the schedule from the schedule map, we should also kill/cancel all jobs associated with it.

Additionally, when adding this functionality, can you add some unit tests to ensure that this functionality works as expected?

**Comment by ralph-m** [comment]
@enragedginger I added a fully functioning method including a unit test. Let me know if you have any proposal or further improvements.

**Comment by enragedginger** [comment]
Hello again,

I finally got around to looking at this. It looks like there's a large number of merge conflicts. It looks like there's some auto-formatting fighting that's going on here. Can you make another commit to correct this so that your commit is only affecting the lines you're actually changing and isn't reformatting other lines?

**Comment by krishnangc** [comment]
Hi,
I needed this function. When will this be merged?

**Comment by enragedginger** [comment]
Per my previous comment, the merge conflicts need to be resolved and the build needs to pass. After that, we should be able to merge it.

@ralph-m Are you still interested in correcting the merge conflict?

@krishnangc If timing is an issue, you can always clone the project down and push out a local build to get you by for now.

**Comment by enragedginger** [comment]
LGTM

Thank you!

**Pull request merged**
