### PR TITLE
Scala 2.13 support

### PR DESCRIPTION
**Pull request by tanacasino**
Update dependencies and set Scala version

### CODE REVIEW

**Comment by qux42** [comment]
I would really appreciate if this gets soon merged and released :)

**Comment by shimamoto** [comment]
I'm also using this library, so it would be great if you could release a version with Scala 2.13 support.

**Comment by enragedginger** [comment]
Hi everybody. I've pushed out the 2.13 build. Let me know if you run into any issues.

**Comment by shimamoto** [comment]
@enragedginger Thank you so much, I appreciate it!

**Pull request merged**
